//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.CelloManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.CelloManager.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already finished ähnelt.
        /// </summary>
        public static string CommonCompledLabel {
            get {
                return ResourceManager.GetString("CommonCompledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        /// </summary>
        public static string CommonLabelOf {
            get {
                return ResourceManager.GetString("CommonLabelOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string CommonLabelRemove {
            get {
                return ResourceManager.GetString("CommonLabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string ComonLabelAdd {
            get {
                return ResourceManager.GetString("ComonLabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given address is wrong. ähnelt.
        /// </summary>
        public static string DnsValidationMessage {
            get {
                return ResourceManager.GetString("DnsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spool Order in Atttached File ähnelt.
        /// </summary>
        public static string EmailerMessageBody {
            get {
                return ResourceManager.GetString("EmailerMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spool Order ähnelt.
        /// </summary>
        public static string EmailerMessageSubject {
            get {
                return ResourceManager.GetString("EmailerMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name can not be empty! ähnelt.
        /// </summary>
        public static string LabelErrorNonEmptyString {
            get {
                return ResourceManager.GetString("LabelErrorNonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Negative is not allowed! ähnelt.
        /// </summary>
        public static string LabelErrorNonNegativeInt {
            get {
                return ResourceManager.GetString("LabelErrorNonNegativeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refill ähnelt.
        /// </summary>
        public static string LabelMainWindowRefill {
            get {
                return ResourceManager.GetString("LabelMainWindowRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string LabelOptions {
            get {
                return ResourceManager.GetString("LabelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updates ähnelt.
        /// </summary>
        public static string LabelOptionsAutoUpdate {
            get {
                return ResourceManager.GetString("LabelOptionsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Edit ähnelt.
        /// </summary>
        public static string LabelOptionsBeginEdit {
            get {
                return ResourceManager.GetString("LabelOptionsBeginEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string LabelOptionsCancel {
            get {
                return ResourceManager.GetString("LabelOptionsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for Updates ähnelt.
        /// </summary>
        public static string LabelOptionsCheckforUpdates {
            get {
                return ResourceManager.GetString("LabelOptionsCheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string LabelOptionsCommit {
            get {
                return ResourceManager.GetString("LabelOptionsCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install ähnelt.
        /// </summary>
        public static string LabelOptionsInstallUpdates {
            get {
                return ResourceManager.GetString("LabelOptionsInstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string LabelOptionsLayout {
            get {
                return ResourceManager.GetString("LabelOptionsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        public static string LabelOptionsLayoutAmount {
            get {
                return ResourceManager.GetString("LabelOptionsLayoutAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string LabelOptionsLayoutName {
            get {
                return ResourceManager.GetString("LabelOptionsLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Needed Count ähnelt.
        /// </summary>
        public static string LabelOptionsLayoutNeedAmount {
            get {
                return ResourceManager.GetString("LabelOptionsLayoutNeedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string LabelOptionsLayoutType {
            get {
                return ResourceManager.GetString("LabelOptionsLayoutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MainWindowFileMenuLabel {
            get {
                return ResourceManager.GetString("MainWindowFileMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        public static string MainWindowMenuEditorLabel {
            get {
                return ResourceManager.GetString("MainWindowMenuEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orders ähnelt.
        /// </summary>
        public static string MainWindowMenuOrdersLabel {
            get {
                return ResourceManager.GetString("MainWindowMenuOrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MainWindowMenuSettingsLabel {
            get {
                return ResourceManager.GetString("MainWindowMenuSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string MainWindowMenuViewLabel {
            get {
                return ResourceManager.GetString("MainWindowMenuViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum Spool Historie must be a Positive Number. ähnelt.
        /// </summary>
        public static string MaximumSpoolHistorieValidation {
            get {
                return ResourceManager.GetString("MaximumSpoolHistorieValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordered Count ähnelt.
        /// </summary>
        public static string OderViewOrderedCount {
            get {
                return ResourceManager.GetString("OderViewOrderedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string OptionsWindowCancel {
            get {
                return ResourceManager.GetString("OptionsWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Printer: ähnelt.
        /// </summary>
        public static string OptionsWindowDefaultPrinter {
            get {
                return ResourceManager.GetString("OptionsWindowDefaultPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DNS: ähnelt.
        /// </summary>
        public static string OptionsWindowDNSLabel {
            get {
                return ResourceManager.GetString("OptionsWindowDNSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail To: ähnelt.
        /// </summary>
        public static string OptionsWindowMailTo {
            get {
                return ResourceManager.GetString("OptionsWindowMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old Order Maximum ähnelt.
        /// </summary>
        public static string OptionsWindowMaximumSpoolHistorie {
            get {
                return ResourceManager.GetString("OptionsWindowMaximumSpoolHistorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order Send Mode: ähnelt.
        /// </summary>
        public static string OptionsWindowPrinterType {
            get {
                return ResourceManager.GetString("OptionsWindowPrinterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purge: ähnelt.
        /// </summary>
        public static string OptionsWindowPurge {
            get {
                return ResourceManager.GetString("OptionsWindowPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string OptionsWindowSaveButton {
            get {
                return ResourceManager.GetString("OptionsWindowSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minmum Order Count: ähnelt.
        /// </summary>
        public static string OptionsWindowThreshold {
            get {
                return ResourceManager.GetString("OptionsWindowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check All ähnelt.
        /// </summary>
        public static string OrderCompledWindowCheckAllLabel {
            get {
                return ResourceManager.GetString("OrderCompledWindowCheckAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commit ähnelt.
        /// </summary>
        public static string OrderCompledWindowCommitLabel {
            get {
                return ResourceManager.GetString("OrderCompledWindowCommitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The order will not be completed. Proceed anyway. ähnelt.
        /// </summary>
        public static string OrderCompledWindowNotCheckedMessage {
            get {
                return ResourceManager.GetString("OrderCompledWindowNotCheckedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id: ähnelt.
        /// </summary>
        public static string OrderViewIdLabel {
            get {
                return ResourceManager.GetString("OrderViewIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orders ähnelt.
        /// </summary>
        public static string OrderViewTitle {
            get {
                return ResourceManager.GetString("OrderViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Film order: ähnelt.
        /// </summary>
        public static string PrintOrderHeaderText {
            get {
                return ResourceManager.GetString("PrintOrderHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string RefillPrinterTypeEmail {
            get {
                return ResourceManager.GetString("RefillPrinterTypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        public static string RefillPrinterTypePrint {
            get {
                return ResourceManager.GetString("RefillPrinterTypePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag and drop the columns here ähnelt.
        /// </summary>
        public static string SpoolGridGroupingBoxLabel {
            get {
                return ResourceManager.GetString("SpoolGridGroupingBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add New Spool ähnelt.
        /// </summary>
        public static string SpoolGridViewAddNewRowLabel {
            get {
                return ResourceManager.GetString("SpoolGridViewAddNewRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given e-mail address is wrong. ähnelt.
        /// </summary>
        public static string TargetEmailValidation {
            get {
                return ResourceManager.GetString("TargetEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thershold Must be Positive ähnelt.
        /// </summary>
        public static string ThresholdValidation {
            get {
                return ResourceManager.GetString("ThresholdValidation", resourceCulture);
            }
        }
    }
}
