//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoReleaser.SolutionLoader.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoReleaser.SolutionLoader.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;About... ähnelt.
        /// </summary>
        public static string About_menu {
            get {
                return ResourceManager.GetString("About menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;About Versioning Controlled Build ähnelt.
        /// </summary>
        public static string About_menu_caption {
            get {
                return ResourceManager.GetString("About menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Versioning Controlled Build ähnelt.
        /// </summary>
        public static string About_toolTip {
            get {
                return ResourceManager.GetString("About toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure to continue? ähnelt.
        /// </summary>
        public static string Are_you_sure_to_continue {
            get {
                return ResourceManager.GetString("Are you sure to continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Version file not found&gt;  ähnelt.
        /// </summary>
        public static string AssemblyInfo_file_not_found_in_project {
            get {
                return ResourceManager.GetString("AssemblyInfo file not found in project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;*&apos; may appear only at the end of version string and it must be a single. ähnelt.
        /// </summary>
        public static string Asterisk_may_appear_only_at_the_end_of_version_string {
            get {
                return ResourceManager.GetString("Asterisk may appear only at the end of version string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version may not contain &apos;*&apos; character. ähnelt.
        /// </summary>
        public static string Asterisk_not_allowed {
            get {
                return ResourceManager.GetString("Asterisk not allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Solution with Updated Versions ähnelt.
        /// </summary>
        public static string Build_solution_toolTip {
            get {
                return ResourceManager.GetString("Build solution toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Build with Versions Updated ähnelt.
        /// </summary>
        public static string Build_with_Updated_Versions_menu_caption {
            get {
                return ResourceManager.GetString("Build with Updated Versions menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save configuration file: ähnelt.
        /// </summary>
        public static string Cannot_save_configuration_file {
            get {
                return ResourceManager.GetString("Cannot save configuration file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save file: ähnelt.
        /// </summary>
        public static string Cannot_save_file {
            get {
                return ResourceManager.GetString("Cannot save file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check permissions and security settings. ähnelt.
        /// </summary>
        public static string Check_permissions {
            get {
                return ResourceManager.GetString("Check permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Settings... ähnelt.
        /// </summary>
        public static string Configure_menu_caption {
            get {
                return ResourceManager.GetString("Configure menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure VCB ähnelt.
        /// </summary>
        public static string Configure_toolTip {
            get {
                return ResourceManager.GetString("Configure toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Blank] ähnelt.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error starting Versioning Controlled Build add-in ähnelt.
        /// </summary>
        public static string Error_starting_VCB {
            get {
                return ResourceManager.GetString("Error starting VCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versioning Controlled Build Error ähnelt.
        /// </summary>
        public static string Error_title {
            get {
                return ResourceManager.GetString("Error title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E&amp;xport Versions to File... ähnelt.
        /// </summary>
        public static string Export_Versions_menu_caption {
            get {
                return ResourceManager.GetString("Export Versions menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Versions ähnelt.
        /// </summary>
        public static string Export_versions_toolTip {
            get {
                return ResourceManager.GetString("Export versions toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load settings from configuration file. ähnelt.
        /// </summary>
        public static string Failed_to_load_configuration_file {
            get {
                return ResourceManager.GetString("Failed to load configuration file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File filter cannot contain any of the following characters: ähnelt.
        /// </summary>
        public static string File_filter_cannot_contain_any_of_the_characters {
            get {
                return ResourceManager.GetString("File filter cannot contain any of the characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;GUI... ähnelt.
        /// </summary>
        public static string GUI_menu_caption {
            get {
                return ResourceManager.GetString("GUI menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versioning Controlled Build GUI ähnelt.
        /// </summary>
        public static string GUI_ToolTip {
            get {
                return ResourceManager.GetString("GUI ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more selected project(s) have already higher version than one to be applied. ähnelt.
        /// </summary>
        public static string Higher_version_warning {
            get {
                return ResourceManager.GetString("Higher version warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;invalid&gt; ähnelt.
        /// </summary>
        public static string Invalid_version {
            get {
                return ResourceManager.GetString("Invalid version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid version pattern [{0}] ähnelt.
        /// </summary>
        public static string Invalid_version_pattern {
            get {
                return ResourceManager.GetString("Invalid version pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String [{0}] is not a valid version. {1} ähnelt.
        /// </summary>
        public static string Invalid_version_string {
            get {
                return ResourceManager.GetString("Invalid version string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must restart VS IDE to make changes effective. ähnelt.
        /// </summary>
        public static string Must_restart_VS_IDE {
            get {
                return ResourceManager.GetString("Must restart VS IDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Print Versions... ähnelt.
        /// </summary>
        public static string Print_Versions_menu_caption {
            get {
                return ResourceManager.GetString("Print Versions menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Versions ähnelt.
        /// </summary>
        public static string Print_versions_toolTip {
            get {
                return ResourceManager.GetString("Print versions toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rebuild Solution with Updated Versions ähnelt.
        /// </summary>
        public static string Rebuild_solution_toolTip {
            get {
                return ResourceManager.GetString("Rebuild solution toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Rebuild with Versions Updated ähnelt.
        /// </summary>
        public static string Rebuild_with_Updated_Versions_menu_caption {
            get {
                return ResourceManager.GetString("Rebuild with Updated Versions menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Error ähnelt.
        /// </summary>
        public static string Save_Error {
            get {
                return ResourceManager.GetString("Save Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &amp;Updated Versions ähnelt.
        /// </summary>
        public static string Save_Updated_Versions_menu_caption {
            get {
                return ResourceManager.GetString("Save Updated Versions menu caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select root folder of IIS projects ähnelt.
        /// </summary>
        public static string Select_IIS_Root_description {
            get {
                return ResourceManager.GetString("Select IIS Root description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select SourceSafe Root Folder ähnelt.
        /// </summary>
        public static string Select_SourceSafe_Folder_caption {
            get {
                return ResourceManager.GetString("Select SourceSafe Folder caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Settings... ähnelt.
        /// </summary>
        public static string Settings_menu {
            get {
                return ResourceManager.GetString("Settings menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source Safe Executable|ss.exe ähnelt.
        /// </summary>
        public static string SoursceSafe_exe_Filter {
            get {
                return ResourceManager.GetString("SoursceSafe exe Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution Versions ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Versions ähnelt.
        /// </summary>
        public static string Update_versions_toolTip {
            get {
                return ResourceManager.GetString("Update versions toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default settings will be used. ähnelt.
        /// </summary>
        public static string Using_default_configuration {
            get {
                return ResourceManager.GetString("Using default configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version format error ähnelt.
        /// </summary>
        public static string Version_format_error {
            get {
                return ResourceManager.GetString("Version format error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version may consist of non-negative integers only. ähnelt.
        /// </summary>
        public static string Version_may_consist_of_non_negative_integers {
            get {
                return ResourceManager.GetString("Version may consist of non-negative integers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version may consist of non-negative integers or a single asterisk character only. ähnelt.
        /// </summary>
        public static string Version_may_consist_of_non_negative_integers_or_a_single_asterisk_character {
            get {
                return ResourceManager.GetString("Version may consist of non-negative integers or a single asterisk character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version must contain integers smaller than {0} ähnelt.
        /// </summary>
        public static string Version_must_be_smaller_than {
            get {
                return ResourceManager.GetString("Version must be smaller than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version must consist of at least {0} dot-separated components. ähnelt.
        /// </summary>
        public static string Version_must_consist_of_at_least_N_components {
            get {
                return ResourceManager.GetString("Version must consist of at least N components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version must consist of at most {0} dot-separated components. ähnelt.
        /// </summary>
        public static string Version_must_consist_of_at_most_N_components {
            get {
                return ResourceManager.GetString("Version must consist of at most N components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version must not contain negative integers. ähnelt.
        /// </summary>
        public static string Version_must_not_contain_negative_integers {
            get {
                return ResourceManager.GetString("Version must not contain negative integers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version must not end with a dot character. ähnelt.
        /// </summary>
        public static string Version_must_not_end_with_dot {
            get {
                return ResourceManager.GetString("Version must not end with dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;not found&gt; ähnelt.
        /// </summary>
        public static string Version_not_found {
            get {
                return ResourceManager.GetString("Version not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version overflow for &apos;{0}&apos; in project(s): {1} ähnelt.
        /// </summary>
        public static string Version_overflow_occured_for_projects {
            get {
                return ResourceManager.GetString("Version overflow occured for projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versions successfully updated ähnelt.
        /// </summary>
        public static string Versions_successfully_updated {
            get {
                return ResourceManager.GetString("Versions successfully updated", resourceCulture);
            }
        }
    }
}
